language: node_js
node_js:
- "0.10"
#- "0.8"
#- "0.6"
env:
  global:
    # Sauce Labs: (prinzmajus/thmcards) 1. User, 2. Access-Key
    - secure: "BxceQZMQnKlq3vyYGTmwHK8THaQinsumatiXhwIcA7fWS1NsNdw2ci5KPDqbDUh2trnVF1IADlOCZCAUiQ5HBUZOEZxkPWdCNzZDMsWB8XTlSIYFMfpWZZE8m89slIFmOUfm6+8KVlOfZcpHBx3ri8TPwr281IkgoMhbYJcjpwI="
    - secure: "JgtmzxUu55wJM1TL5hnldFv3E6xtmW4qMAqcujHkNM5YB/bX+KQfBqUGSSXGCsFd/0ELzkOt5gpbxSCLoj9zC/+DMw7IQsBJXrtrkg7yqodrGymTnC/hyV8QuBDkaG2524kxh2hvKAWvfGCJwgSeoHQ6k9IToBpELswbvaLKMII="
  matrix:
    #- "BROWSER='firefox::Windows 7'"
    - "BROWSER='chrome::Windows 7'"
services:
  - couchdb
before_install:
  # Install tools required for GUI testing
  - "gem install selenium-webdriver"
  - "curl https://gist.github.com/santiycr/5139565/raw/sauce_connect_setup.sh | bash"
  # Setup CouchDB
  - "python createviews.py"
before_script:
  # Download dependencies, install packages, run server
  - "npm -g install forever"
  - "forever start app.js"
script:
  # Run tests
  - "ruby saucelabs.rb"
deploy:
  provider: cloudcontrol
  email:
    secure: "PMxOnzO4j+1kaREs7mdkSc7l/DR3pTV5M8sh9IwaR3IVRowb3mzdDc64vhu3hUytDZrZlTcHoGuU+Ttj0y91Nd14YY2G8kPys6MuL49kjPEG50WDgwMv/P9wxG47OanFUf8wMzV1hw4uCgo6PGaVyEi5YNKbb2pkiQl2YtoZ9Ro="
  password:
    secure: "dxk5ZJc1v5nup91r694Sjv/ouLwhBFvuXN2BeUx7P/PMF0v2r7P4fjpFOh08GWbAHqN8qXUiV+bfhlfU0yb6l8l80Lr2hzh5Z4SyiWnHMhS0CNWy+WkDVD3H7BKKQg/rT4cabl/6L313DHEVEqkPQp2d2aadl+ESpGI2Zkwosxw="
  deployment: arscards/default
  on:
    repo: prinzmajus/thmcards
addons:
  sauce_connect: true
